#!/bin/bash

gettopdir()
{
    local here=`pwd`
    local topdir=$here
    local topfile=bos/bin/bosm
    while [ ! -f $topfile -a $topdir != "/" ]; do
        cd .. > /dev/null
        topdir=`pwd`
    done
    cd $here > /dev/null

    if [ -f "$topdir/$topfile" ]; then
        echo $topdir
    else
        echo -e "\nunable to locate topdir, must run from within bosm tree.\n" >&2
        exit -1
    fi
}

getpath()
{
    local path=$PATH
	local topdir=$(gettopdir)
    local bindir=$topdir/bos/bin
    [ -e "$topdir" ] && path=$bindir:${PATH//$bindir:}
    echo $path
}

export PATH=$(getpath)
