#!/usr/bin/env python
#
# Copyright (C) 2012        SWOAG Technology
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os, sys, shutil

from bomb.main import Bos
from bomb.log import Blog
from bomb.package import BosPackage
from bomb.util import bos_run


def bosinstall():

    name = sys.argv[1]
    pkg = BosPackage.open(name)

    ret,logname = pkg.install()
    if 0 != ret:
        Blog.fatal('%s failed to install, see log at: %s' % (name, logname))
    else:
        Bos.touch(Bos.statesdir + name + '.d')


if __name__ == '__main__':
    try:
        ret = bosinstall()
    except Exception:
        ret = 1
        if os.environ['_BOS_TRACE_'] == 'yes':
            import traceback
            traceback.print_exc(5)
    sys.exit(ret)
